import "server-only";
import { db } from "./db";
import { clientOf, tokenRequest } from "./zohoOAuth";
import type { CertRow } from "./types";

/*
 * The master certificate register — a Zoho Sheet, one row per certificate issued: Serial, Certificate No., Name,
 * Training location ("course conducted at"), Course, Date. The Fulfillment board appends a batch of participants at
 * the end, continuing the serial from the last row. Connected once by Admin with a one-time code from the Zoho API
 * console, generated by an account that can edit the sheet (digital@thinkhealth.in); its refresh token lives only in
 * MongoDB kv `zoho_sheet:master`.
 *
 * Columns are found by their header (first row), so moving a column in the sheet doesn't break anything; the date is
 * written the way the last row shows it.
 */

const SHEET_API = process.env.ZOHO_SHEET_API ?? "https://sheet.zoho.in";
export const SHEET_SCOPES = "ZohoSheet.dataAPI.READ,ZohoSheet.dataAPI.UPDATE";
const KEY = "zoho_sheet:master";
const LOCK = "zoho_sheet_lock";
const LOCK_MS = 60_000;

type Conn = {
  _id: string;
  resourceId: string;
  worksheet: string;
  clientId: string;
  clientSecret: string;
  refreshToken: string;
  token?: { value: string; expiresAt: number };
  connectedAt: string;
  connectedBy: string;
};
export type SheetInfo = { resourceId: string; worksheet: string; connectedAt: string; connectedBy: string };

const kv = async () => (await db()).collection<Conn>("kv");

export async function sheetInfo(): Promise<SheetInfo | null> {
  const c = await (await kv()).findOne({ _id: KEY });
  return c ? { resourceId: c.resourceId, worksheet: c.worksheet, connectedAt: c.connectedAt, connectedBy: c.connectedBy } : null;
}

/** The workbook id from a sheet link (…/sheet/open/<id>?sheetid=0) or the id itself. */
export function resourceIdOf(link: string): string {
  const m = link.trim().match(/\/open\/([A-Za-z0-9]+)/) ?? link.trim().match(/^([A-Za-z0-9]{20,})$/);
  if (!m) throw new Error("That doesn't look like a Zoho Sheet link");
  return m[1];
}

async function accessFor(c: Conn, force = false): Promise<string> {
  if (!force && c.token && Date.now() < c.token.expiresAt - 5 * 60_000) return c.token.value;
  const t = await tokenRequest({ grant_type: "refresh_token", client_id: c.clientId, client_secret: c.clientSecret, refresh_token: c.refreshToken })
    .catch((e: Error) => { throw new Error(`Zoho Sheet sign-in failed — Admin may need to connect the sheet again (${e.message})`); });
  c.token = { value: t.access_token!, expiresAt: Date.now() + (t.expires_in ?? 3600) * 1000 };
  await (await kv()).updateOne({ _id: c._id }, { $set: { token: c.token } });
  return c.token.value;
}

type SheetRes = { status?: string; error_message?: string; error_code?: number; [k: string]: unknown };

/** One Data API call (form POST with `method`). Throws Zoho's message when it says "failure". */
async function call(c: Pick<Conn, "resourceId">, token: string, params: Record<string, string>): Promise<SheetRes> {
  const res = await fetch(`${SHEET_API}/api/v2/${c.resourceId}`, {
    method: "POST",
    headers: { Authorization: `Zoho-oauthtoken ${token}` },
    body: new URLSearchParams(params),
    cache: "no-store",
  });
  const json = (await res.json().catch(() => ({}))) as SheetRes;
  if (res.status === 401) throw Object.assign(new Error("unauthorized"), { status: 401 });
  if (!res.ok || json.status === "failure") throw new Error(`Zoho Sheet: ${json.error_message ?? `error ${json.error_code ?? res.status}`}`);
  return json;
}

async function sheetCall(params: Record<string, string>): Promise<SheetRes> {
  const c = await (await kv()).findOne({ _id: KEY });
  if (!c) throw new Error("The master sheet isn't connected yet — Admin connects it once");
  const p = { worksheet_name: c.worksheet, ...params };
  try {
    return await call(c, await accessFor(c), p);
  } catch (e) {
    if ((e as { status?: number }).status === 401) return call(c, await accessFor(c, true), p); // token revoked early
    throw e;
  }
}

/* ---------------- The register's columns ---------------- */

export type Columns = { serial?: string; certNo?: string; name?: string; location?: string; course?: string; date?: string };
const COLUMN_TESTS: [keyof Columns, RegExp, RegExp?][] = [
  ["certNo", /cert/i],
  ["serial", /^\s*(s\.?\s*no|sr\.?\s*no|sl\.?\s*no|serial|#)/i],
  ["date", /date/i],
  ["location", /location|conducted|venue|place|organi[sz]ation|company/i],
  ["course", /course|training|program/i],
  ["name", /name/i],
];

/** Which header is which field (each header used once, in the order above). */
export function findColumns(headers: string[]): Columns {
  const out: Columns = {};
  const used = new Set<string>();
  for (const [field, re] of COLUMN_TESTS) {
    const h = headers.find((x) => !used.has(x) && re.test(x));
    if (h) { out[field] = h; used.add(h); }
  }
  return out;
}

const REQUIRED: (keyof Columns)[] = ["serial", "certNo", "name", "date"];
const FIELD_LABEL: Record<keyof Columns, string> = { serial: "Serial", certNo: "Certificate No.", name: "Name", location: "Training location", course: "Course", date: "Date" };

export type Register = {
  headers: string[];
  columns: Columns;
  missing: string[]; // fields with no column — rows can't be added until fixed
  count: number;
  lastSerial: number;
  /** The last rows as they sit in the sheet, oldest first (header → value). */
  last: Record<string, string>[];
  dateStyle: DateStyle;
};

type DateStyle = "dd/mm/yyyy" | "dd-mm-yyyy" | "yyyy-mm-dd" | "dd-Mon-yyyy" | "dd Mon yyyy";
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

function styleOf(v: string | undefined): DateStyle {
  const s = (v ?? "").trim();
  if (/^\d{1,2}-\d{1,2}-\d{4}$/.test(s)) return "dd-mm-yyyy";
  if (/^\d{4}-\d{2}-\d{2}/.test(s)) return "yyyy-mm-dd";
  if (/^\d{1,2}-[A-Za-z]{3}-\d{4}$/.test(s)) return "dd-Mon-yyyy";
  if (/^\d{1,2} [A-Za-z]{3,} \d{4}$/.test(s)) return "dd Mon yyyy";
  return "dd/mm/yyyy";
}

/** "2026-10-06" in the sheet's own date style. */
export function sheetDate(ymd: string, style: DateStyle): string {
  const [y, m, d] = ymd.slice(0, 10).split("-");
  switch (style) {
    case "dd-mm-yyyy": return `${d}-${m}-${y}`;
    case "yyyy-mm-dd": return `${y}-${m}-${d}`;
    case "dd-Mon-yyyy": return `${d}-${MONTHS[Number(m) - 1]}-${y}`;
    case "dd Mon yyyy": return `${d} ${MONTHS[Number(m) - 1]} ${y}`;
    default: return `${d}/${m}/${y}`;
  }
}

const str = (v: unknown) => (v == null ? "" : String(v));

/** Reads the whole register (one call): its columns, how many rows, the last serial and the last rows. */
export async function readRegister(): Promise<Register> {
  const r = await sheetCall({ method: "worksheet.records.fetch", header_row: "1" });
  const records = ((r.records as Record<string, unknown>[] | undefined) ?? []).map((rec) => {
    const { row_index, ...rest } = rec; // eslint-disable-line @typescript-eslint/no-unused-vars
    return Object.fromEntries(Object.entries(rest).map(([k, v]) => [k, str(v)]));
  });
  const headers = (r.columns as string[] | undefined) ?? [...new Set(records.flatMap((x) => Object.keys(x)))];
  const columns = findColumns(headers);
  const missing = REQUIRED.filter((f) => !columns[f]).map((f) => FIELD_LABEL[f]);
  // Highest serial in the sheet (not just the last row's, in case rows were sorted).
  const serials = columns.serial ? records.map((x) => Number.parseInt(x[columns.serial!].replace(/[^\d]/g, ""), 10)).filter(Number.isFinite) : [];
  const filled = records.filter((x) => Object.values(x).some((v) => v.trim()));
  return {
    headers, columns, missing,
    count: filled.length,
    lastSerial: serials.length ? Math.max(...serials) : 0,
    last: filled.slice(-2),
    dateStyle: styleOf(columns.date ? filled.at(-1)?.[columns.date] : undefined),
  };
}

/** A batch's rows as they'll sit in the sheet (header → value). */
export function sheetRows(reg: Register, rows: CertRow[]): Record<string, string>[] {
  const c = reg.columns;
  return rows.map((x) => {
    const out: Record<string, string> = {};
    if (c.serial) out[c.serial] = String(x.serial);
    if (c.certNo) out[c.certNo] = x.certNo;
    if (c.name) out[c.name] = x.name;
    if (c.location) out[c.location] = x.location;
    if (c.course) out[c.course] = x.course;
    if (c.date) out[c.date] = sheetDate(x.date, reg.dateStyle);
    return out;
  });
}

/* ---------------- Adding a batch ---------------- */

async function lock<T>(fn: () => Promise<T>): Promise<T> {
  const owner = Math.random().toString(36).slice(2);
  const now = Date.now();
  const col = (await db()).collection<{ _id: string; until?: number; owner?: string }>("kv");
  let got = false;
  try {
    const r = await col.findOneAndUpdate(
      { _id: LOCK, $or: [{ until: { $lt: now } }, { until: { $exists: false } }] },
      { $set: { until: now + LOCK_MS, owner } },
      { upsert: true, returnDocument: "after" },
    );
    got = r?.owner === owner;
  } catch (e) {
    if ((e as { code?: number }).code !== 11000) throw e;
  }
  if (!got) throw new Error("Someone else is adding names to the sheet right now — try again in a minute");
  try {
    return await fn();
  } finally {
    await col.updateOne({ _id: LOCK, owner }, { $set: { until: 0 } });
  }
}

/**
 * Appends the batch at the end of the sheet. Serials are taken again from the sheet right now (one batch at a time),
 * so two people never get the same numbers; `make` builds the rows from the first free serial.
 */
export async function appendBatch(make: (firstSerial: number) => CertRow[]): Promise<{ rows: CertRow[]; register: Register }> {
  return lock(async () => {
    const register = await readRegister();
    if (register.missing.length) throw new Error(`The sheet has no ${register.missing.join(", ")} column — check its first row`);
    const rows = make(register.lastSerial + 1);
    await sheetCall({ method: "worksheet.records.add", header_row: "1", json_data: JSON.stringify(sheetRows(register, rows)) });
    return { rows, register };
  });
}

/**
 * Admin connects the sheet: swaps the one-time code for a refresh token, finds the worksheet (the first one, unless
 * named) and reads the register once to check its columns.
 */
export async function connectSheet(input: { link: string; worksheet?: string; code: string; clientId?: string; clientSecret?: string; by: string }) {
  const resourceId = resourceIdOf(input.link);
  const { clientId, clientSecret } = clientOf(input);
  const t = await tokenRequest({ grant_type: "authorization_code", client_id: clientId, client_secret: clientSecret, code: input.code.trim() });
  if (!t.refresh_token) throw new Error("Zoho didn't return a refresh token — generate a new code and try again");
  const list = await call({ resourceId }, t.access_token!, { method: "worksheet.list" });
  const names = ((list.worksheet_names as { worksheet_name: string }[] | undefined) ?? []).map((w) => w.worksheet_name);
  if (!names.length) throw new Error("Couldn't read the sheet's worksheets — is this account allowed to edit it?");
  const worksheet = input.worksheet?.trim() && names.includes(input.worksheet.trim()) ? input.worksheet.trim() : names[0];
  const doc: Conn = {
    _id: KEY, resourceId, worksheet, clientId, clientSecret, refreshToken: t.refresh_token,
    token: { value: t.access_token!, expiresAt: Date.now() + (t.expires_in ?? 3600) * 1000 },
    connectedAt: new Date().toISOString(), connectedBy: input.by,
  };
  await (await kv()).replaceOne({ _id: KEY }, doc, { upsert: true });
  return { info: (await sheetInfo())!, worksheets: names, register: await readRegister() };
}
