import { memberIdOf, signedInMember, unauthorized } from "@/lib/auth";
import { boardsFor, isAdmin } from "@/lib/roles";
import { SHEET_SCOPES, connectSheet, readRegister, sheetInfo } from "@/lib/zohoSheet";

export const dynamic = "force-dynamic";

// The master certificate sheet (Zoho Sheet). GET — is it connected; GET ?check=1 (Fulfillment) — its columns, row count
// and last rows, to see the dashboard reads it right. POST { link, code, clientId?, clientSecret?, worksheet? } — Admin
// connects it with a one-time code generated by an account that can edit the sheet (digital@thinkhealth.in).

export async function GET(request: Request) {
  if (!memberIdOf(request)) return unauthorized();
  try {
    const info = await sheetInfo();
    if (!new URL(request.url).searchParams.get("check") || !info) return Response.json({ sheet: info, scopes: SHEET_SCOPES });
    const me = await signedInMember(request);
    if (!me || !boardsFor(me).includes("fulfil")) return Response.json({ error: "Only the Fulfillment board reads the sheet" }, { status: 403 });
    return Response.json({ sheet: info, scopes: SHEET_SCOPES, register: await readRegister() });
  } catch (e) {
    return Response.json({ error: e instanceof Error ? e.message : "Couldn't read the sheet" }, { status: 502 });
  }
}

export async function POST(request: Request) {
  const me = await signedInMember(request);
  if (!me) return unauthorized();
  if (!isAdmin(me)) return Response.json({ error: "Only Admin connects the sheet" }, { status: 403 });
  const body = (await request.json().catch(() => ({}))) as { link?: string; code?: string; clientId?: string; clientSecret?: string; worksheet?: string };
  if (!body.link || !body.code) return Response.json({ error: "Sheet link and code are needed" }, { status: 400 });
  try {
    const r = await connectSheet({ link: body.link, code: body.code, clientId: body.clientId, clientSecret: body.clientSecret, worksheet: body.worksheet, by: me.name });
    return Response.json({ ok: true, ...r });
  } catch (e) {
    return Response.json({ error: e instanceof Error ? e.message : "Couldn't connect" }, { status: 400 });
  }
}
